2025-01-24 10:06:33,139 (14572/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-24 10:06:33,238 (14572/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/usr/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/usr/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2025-01-24 10:08:03,432 (14876/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-24 10:08:20,885 (15015/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-01-24 10:08:56,211 (15146/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
